### ISSUE TITLE
Invalida root snapshot

### ISSUE THREAD

**Issue by freddieee** [onflow/full-observer-node-example#4]
Hey, I was trying to set up an observer node connectting to the mainnet, but getting this erros. Can you plz help take a look?

I am pretty sure I downloaded the snapshot data and set the host for mainnet.

`{"level":"fatal","node_role":"consensus_follower","node_id":"not set","error":"cannot bootstrap invalid root snapshot: root block seal for wrong execution result (904bd981febcb1b358dfc5974cb3ea1a67cb40afd00bc692c8f21ce42d726a37 != 83aeb7ae2457362598c6dba06955839aae13b8242382afdb4a98217ef27e82cf)","time":"2021-10-29T08:37:22Z","message":"could not bootstrap protocol state"}`

**Comment by peterargue** [comment]
@freddieee Thanks for reporting this. It looks like the bootstrap file in the GCS bucket is from mainnet 13. I'll update that and submit a PR with details.

**Comment by peterargue** [comment]
I've updated the root protocol snapshot in GCS for mainnet (testnet will be updated after the fork next week). 

That in addition to PR #5 should help get this working for you @freddieee

**Comment by freddieee** [comment]
Hey @peterargue, thanks for the update! It;'s working now.
